"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WorkflowEditorActionType = void 0;
var WorkflowEditorActionType;
(function (WorkflowEditorActionType) {
    WorkflowEditorActionType["SET_WORKFLOW_ID"] = "SET_WORKFLOW_ID";
    WorkflowEditorActionType["SET_GRAPH"] = "SET_GRAPH";
    WorkflowEditorActionType["ADD_NODE"] = "ADD_NODE";
    WorkflowEditorActionType["ADD_EDGE"] = "ADD_EDGE";
    WorkflowEditorActionType["UPDATE_NODE"] = "UPDATE_NODE";
    WorkflowEditorActionType["UPDATE_EDGE"] = "UPDATE_EDGE";
    WorkflowEditorActionType["UPDATE_NODE_POSITION"] = "UPDATE_NODE_POSITION";
    WorkflowEditorActionType["DELETE_NODE"] = "DELETE_NODE";
    WorkflowEditorActionType["DELETE_EDGE"] = "DELETE_EDGE";
    WorkflowEditorActionType["UPDATE_DIRTY_STATE"] = "UPDATE_DIRTY_STATE";
    WorkflowEditorActionType["UPDATE_WORKFLOW"] = "UPDATE_WORKFLOW";
    WorkflowEditorActionType["UPDATE_STATUS"] = "UPDATE_STATUS";
    WorkflowEditorActionType["NODE_EXECUTION_START"] = "NODE_EXECUTION_START";
    WorkflowEditorActionType["NODE_EXECUTION_SUCCESS"] = "NODE_EXECUTION_SUCCESS";
    WorkflowEditorActionType["NODE_EXECUTION_ERROR"] = "NODE_EXECUTION_ERROR";
    WorkflowEditorActionType["RESET_NODE_STATUS"] = "RESET_NODE_STATUS";
    WorkflowEditorActionType["EDGE_EXECUTION_START"] = "EDGE_EXECUTION_START";
    WorkflowEditorActionType["EDGE_EXECUTION_END"] = "EDGE_EXECUTION_END";
})(WorkflowEditorActionType || (exports.WorkflowEditorActionType = WorkflowEditorActionType = {}));
