import type { Metadata } from 'next';
import {Geist, Geist_Mono, Urbanist} from 'next/font/google';
import './globals.css';
import React from 'react';
import { Toaster } from '@/components/ui/sonner';
import { Providers } from '@/app/Provider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const urbanist = Urbanist({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-urbanist', // Defines a CSS variable
    weight: ['300', '400', '500', '600', '700', '900'], // Choose the weights you need
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`no-scrollbar ${urbanist.variable} ${geistSans.variable} ${geistMono.variable} scroll-smooth`}
            suppressHydrationWarning
        >
        <body
            id={'hide-scrollbar'}
            // Combined all font variables here so they are available to all child components
            className={`${geistSans.className} no-scrollbar dark antialiased`}
        >
        <Providers>{children}</Providers>
        <Toaster />
        </body>
        </html>
    );
}
