import { NodeConfigSchema } from "@neuron/shared";
import { buildSharedNodeSchema } from "@neuron/nodes-sdk";

export const OUTPUT_NODE_SCHEMA: NodeConfigSchema = {
    sections: [
        buildSharedNodeSchema()[0],
        {
            id: "output-content",
            title: "Response Content",
            description: "Design the final payload or message generated by this node.",
            layout: "column",
            fields: [
                {
                    id: "template",
                    type: "template",
                    path: "template",
                    label: "Output Template",
                    placeholder: "Hello {{user.name}}, your order #{{order.id}} is complete.",
                    required: true,
                    description: "The main content body. Supports dynamic variables and formatting."
                }
            ]
        },
        {
            id: "format-settings",
            title: "Format & Syntax",
            description: "Define how the output should be structured and rendered.",
            layout: "grid",
            fields: [
                {
                    id: "format-type",
                    type: "select",
                    path: "format.type",
                    label: "Format Type",
                    required: true,
                    options: [
                        { label: "JSON", value: "json" },
                        { label: "Markdown", value: "markdown" },
                        { label: "Plain Text", value: "text" },
                        { label: "HTML", value: "html" },
                        { label: "CSV", value: "csv" }
                    ]
                },
                {
                    id: "minify",
                    type: "switch",
                    path: "format.minify",
                    label: "Minify Output",
                    description: "Remove unnecessary whitespace."
                },
                {
                    id: "syntaxHighlight",
                    type: "switch",
                    path: "format.syntaxHighlight",
                    label: "Syntax Highlighting",
                    description: "Apply code highlighting where applicable."
                }
            ]
        },
        {
            id: "delivery-settings",
            title: "Delivery Configuration",
            description: "Specify where and how the output is delivered.",
            layout: "grid",
            fields: [
                {
                    id: "delivery-mode",
                    type: "select",
                    path: "delivery.mode",
                    label: "Delivery Mode",
                    required: true,
                    options: [
                        { label: "Webhook Response", value: "webhook_response" },
                        { label: "Stored Result", value: "stored_result" },
                        { label: "Notification", value: "notification" }
                    ]
                },
                {
                    id: "statusCode",
                    type: "number",
                    path: "delivery.statusCode",
                    label: "HTTP Status Code",
                    placeholder: "200",
                    hidden: (values) => values.delivery?.mode !== "webhook_response"
                },
                {
                    id: "isPrimary",
                    type: "switch",
                    path: "delivery.isPrimary",
                    label: "Primary Output",
                    description: "Mark this as the main workflow result."
                },
                {
                    id: "includeMetadata",
                    type: "switch",
                    path: "includeMetadata",
                    label: "Include Metadata",
                    description: "Attach execution IDs and timestamps."
                }
            ]
        },
        ...buildSharedNodeSchema().slice(1)
    ]
};