export type ConfigFieldType =
    | "text"
    | "textarea"
    | "template"
    | "number"
    | "switch"
    | "select"
    | "multiselect"
    | "json"
    | "code"
    | "secret"
    | "array"
    | "object"
    | "keyvalue"
    | "dialog";